version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      # Optional environment variables you can override
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
